/**
 * Generated by scripts/generate-icons.mjs — edit the colours there, not here.
 *
 * systray2 takes icon data as base64: an ICO on Windows, a PNG everywhere else.
 * Embedding them keeps the single-file executable free of image assets on disk.
 */
export type TrayStatus = 'connected' | 'idle' | 'error';

const connectedPng =
  'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAyklEQVR42s2XsQ3FIAwFMwG7Ubmn9Bys4BUyiCt28QwovwEJRUQKn4BdXBMFvVNwwD6A8dBkdIEHRgLGBIwCjLkg5RmVdz4VcMAYS8j1Eilr3KxAGAzuiYR/BWgi+A6NCpwfhlfOtwK0IPzxS/T2/FpMeBJwkwU3UpiuJxA3hFdiT0A2CshdwG8Mr/hWgBQEqBVICgKpFRAFAWkFsoJANiWgvgXqRaj+G6ofROpHsYnLSP06Vm9ITLRkJppSE225icHExGhmYjhdyg9N78wx+2KMUgAAAABJRU5ErkJggg==';
const connectedIco =
  'AAABAAEAICAAAAEAIAADAQAAFgAAAIlQTkcNChoKAAAADUlIRFIAAAAgAAAAIAgGAAAAc3p69AAAAMpJREFUeNrNl7ENxSAMBTMBu1G5p/QcrOAVMogrdvEMKL8BCUVECp+AXVwTBb1TcMA+gPHQZHSBB0YCxgSMAoy5IOUZlXc+FXDAGEvI9RIpa9ysQBgM7omEfwVoIvgOjQqcH4ZXzrcCtCD88Uv09vxaTHgScJMFN1KYricQN4RXYk9ANgrIXcBvDK/4VoAUBKgVSAoCqRUQBQFpBbKCQDYloL4F6kWo/huqH0TqR7GJy0j9OlZvSEy0ZCaaUhNtuYnBxMRoZmI4XcoPTe/MMftijFIAAAAASUVORK5CYII=';
const idlePng =
  'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAyUlEQVR42s2XwQnGIAxGO4G7uYKzOEJyyjV0FnfJDNL/oiDFQv2tJod3KZXvUVNNDiA+NBld4IEYgTgBsQBxLkh5huWdTwUcEMcScr1Eyho3KxAGg3si4V8BnAi+g6MC54fhlfOtAC4If/wSvT2/FhOeBNxkwY0UpusJxA3hldgTkI0CchfwG8MrvhVABQFsBZKCQGoFREFAWoGsIJBNCahvgXoRqv+G6geR+lFs4jJSv47VGxITLZmJptREW25iMDExmpkYTpfyA5EqDE/uThJ3AAAAAElFTkSuQmCC';
const idleIco =
  'AAABAAEAICAAAAEAIAACAQAAFgAAAIlQTkcNChoKAAAADUlIRFIAAAAgAAAAIAgGAAAAc3p69AAAAMlJREFUeNrNl8EJxiAMRjuBu7mCszhCcso1dBZ3yQzS/6IgxUL9rSaHdymV71FTTQ4gPjQZXeCBGIE4AbEAcS5IeYblnU8FHBDHEnK9RMoaNysQBoN7IuFfAZwIvoOjAueH4ZXzrQAuCH/8Er09vxYTngTcZMGNFKbrCcQN4ZXYE5CNAnIX8BvDK74VQAUBbAWSgkBqBURBQFqBrCCQTQmob4F6Ear/huoHkfpRbOIyUr+O1RsSEy2ZiabURFtuYjAxMZqZGE6X8gORKgxP7k4SdwAAAABJRU5ErkJggg==';
const errorPng =
  'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAyUlEQVR42s2X0Q2FIAxFnYDF7hcrMAsrdAVnYYlO0BmI7wcSYjCRh9B+nB8juSdSoT0YODQZXeAZIAYSA8JALkh5RuWdTwUcA7GEXC+RssbNCoTB4J5I+FeAJoLv0KjA+WF45XwrQAvCH79Eb8+vxYQnATdZcCOF6XoCcUN4JfYEZKOA3AX8xvCKbwVIQYBagaQgkFoBURCQViArCGRTAupboF6E6r+h+kGkfhSbuIzUr2P1hsRES2aiKTXRlpsYTEyMZiaG06X8AKPRjDFV7EUbAAAAAElFTkSuQmCC';
const errorIco =
  'AAABAAEAICAAAAEAIAACAQAAFgAAAIlQTkcNChoKAAAADUlIRFIAAAAgAAAAIAgGAAAAc3p69AAAAMlJREFUeNrNl9ENhSAMRZ2Axe4XKzALK3QFZ2GJTtAZiO8HEmIwkYfQfpwfI7knUqE9GDg0GV3gGSAGEgPCQC5IeUblnU8FHAOxhFwvkbLGzQqEweCeSPhXgCaC79CowPlheOV8K0ALwh+/RG/Pr8WEJwE3WXAjhel6AnFDeCX2BGSjgNwF/Mbwim8FSEGAWoGkIJBaAVEQkFYgKwhkUwLqW6BehOq/ofpBpH4Um7iM1K9j9YbEREtmoik10ZabGExMjGYmhtOl/ACj0YwxVexFGwAAAABJRU5ErkJggg==';

const icons: Record<TrayStatus, { png: string; ico: string }> = {
  connected: { png: connectedPng, ico: connectedIco },
  idle: { png: idlePng, ico: idleIco },
  error: { png: errorPng, ico: errorIco },
};

export function trayIcon(status: TrayStatus, isWindows: boolean): string {
  const icon = icons[status];
  return isWindows ? icon.ico : icon.png;
}
