/**
 * Generates the tray status icons and writes them into src/tray/icons.ts as base64.
 *
 * Run with `node scripts/generate-icons.mjs` after changing a colour. The output is
 * committed so neither the normal build nor the single-file executable depends on
 * image assets on disk — systray2 takes icon data as base64 anyway (ICO on Windows,
 * PNG elsewhere), so there is nothing to gain from shipping real files.
 */
import { deflateSync } from 'node:zlib';
import { writeFile } from 'node:fs/promises';

const SIZE = 32;

const STATES = {
  connected: [87, 194, 106], // green: Discord has the presence
  idle: [148, 155, 164], // grey: running, no project open
  error: [221, 75, 75], // red: disconnected or failing
};

const crcTable = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});

function crc32(buffer) {
  let c = 0xffffffff;
  for (const byte of buffer) c = crcTable[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([length, body, crc]);
}

/** A filled circle, antialiased by sampling coverage at the edge. */
function drawDot([r, g, b]) {
  const centre = (SIZE - 1) / 2;
  const radius = SIZE / 2 - 1;
  // Each scanline is prefixed with filter byte 0 (None).
  const raw = Buffer.alloc(SIZE * (SIZE * 4 + 1));
  let offset = 0;
  for (let y = 0; y < SIZE; y += 1) {
    raw[offset] = 0;
    offset += 1;
    for (let x = 0; x < SIZE; x += 1) {
      const distance = Math.hypot(x - centre, y - centre);
      const coverage = Math.max(0, Math.min(1, radius - distance + 0.5));
      raw[offset] = r;
      raw[offset + 1] = g;
      raw[offset + 2] = b;
      raw[offset + 3] = Math.round(coverage * 255);
      offset += 4;
    }
  }
  return raw;
}

function toPng(colour) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(SIZE, 0);
  ihdr.writeUInt32BE(SIZE, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // colour type: RGBA
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(drawDot(colour), { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/** Windows accepts a PNG payload inside an ICO container from Vista onwards. */
function toIco(png) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(1, 4); // one image
  const entry = Buffer.alloc(16);
  entry[0] = SIZE;
  entry[1] = SIZE;
  entry[2] = 0; // truecolour, no palette
  entry[3] = 0; // reserved
  entry.writeUInt16LE(1, 4); // colour planes
  entry.writeUInt16LE(32, 6); // bits per pixel
  entry.writeUInt32LE(png.length, 8);
  entry.writeUInt32LE(header.length + entry.length, 12);
  return Buffer.concat([header, entry, png]);
}

const lines = [
  '/**',
  ' * Generated by scripts/generate-icons.mjs — edit the colours there, not here.',
  ' *',
  ' * systray2 takes icon data as base64: an ICO on Windows, a PNG everywhere else.',
  ' * Embedding them keeps the single-file executable free of image assets on disk.',
  ' */',
  "export type TrayStatus = 'connected' | 'idle' | 'error';",
  '',
];

for (const [name, colour] of Object.entries(STATES)) {
  const png = toPng(colour);
  lines.push(
    `const ${name}Png = '${png.toString('base64')}';`,
    `const ${name}Ico = '${toIco(png).toString('base64')}';`,
  );
}

lines.push(
  '',
  'const icons: Record<TrayStatus, { png: string; ico: string }> = {',
  ...Object.keys(STATES).map(
    (name) => `  ${name}: { png: ${name}Png, ico: ${name}Ico },`,
  ),
  '};',
  '',
  'export function trayIcon(status: TrayStatus, isWindows: boolean): string {',
  '  const icon = icons[status];',
  '  return isWindows ? icon.ico : icon.png;',
  '}',
  '',
);

await writeFile('src/tray/icons.ts', lines.join('\n'), 'utf8');
console.log('Wrote src/tray/icons.ts');
